import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider  from "../redux/Providers";
import { store } from "../redux/store"; 
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apana Store",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => (
  <html lang="en">
    <body className={inter.className}>
      <Provider >
        {children}
      </Provider>
    </body>
  </html>
);

export default RootLayout;
